/*****************************************************************
 * Gridnine AB http://www.gridnine.com
 * Project: jasmine
 * This file is auto generated, don't modify it manually
 *****************************************************************/

@file:Suppress("unused","RemoveRedundantQualifierName","MemberVisibilityCanBePrivate","RemoveEmptyPrimaryConstructor", "FunctionName")

package com.gridnine.jasmine.web.core

object RestReflectionUtilsJS{

    fun registerRestWebClasses(){
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerEnum("com.gridnine.jasmine.server.standard.model.rest.RestPropertyTypeDTJS"){com.gridnine.jasmine.server.standard.model.rest.RestPropertyTypeDTJS.valueOf(it)}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerEnum("com.gridnine.jasmine.server.standard.model.rest.DatabasePropertyTypeDTJS"){com.gridnine.jasmine.server.standard.model.rest.DatabasePropertyTypeDTJS.valueOf(it)}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerEnum("com.gridnine.jasmine.server.standard.model.rest.DatabaseCollectionTypeDTJS"){com.gridnine.jasmine.server.standard.model.rest.DatabaseCollectionTypeDTJS.valueOf(it)}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerEnum("com.gridnine.jasmine.server.standard.model.rest.AutocompleteSortOrderDTJS"){com.gridnine.jasmine.server.standard.model.rest.AutocompleteSortOrderDTJS.valueOf(it)}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerEnum("com.gridnine.jasmine.server.standard.model.rest.VMPropertyTypeDTJS"){com.gridnine.jasmine.server.standard.model.rest.VMPropertyTypeDTJS.valueOf(it)}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerEnum("com.gridnine.jasmine.server.standard.model.rest.VSPropertyTypeDTJS"){com.gridnine.jasmine.server.standard.model.rest.VSPropertyTypeDTJS.valueOf(it)}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerEnum("com.gridnine.jasmine.server.standard.model.rest.VVPropertyTypeDTJS"){com.gridnine.jasmine.server.standard.model.rest.VVPropertyTypeDTJS.valueOf(it)}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerEnum("com.gridnine.jasmine.server.standard.model.rest.WidgetTypeDTJS"){com.gridnine.jasmine.server.standard.model.rest.WidgetTypeDTJS.valueOf(it)}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerEnum("com.gridnine.jasmine.server.standard.model.rest.ViewTypeDTJS"){com.gridnine.jasmine.server.standard.model.rest.ViewTypeDTJS.valueOf(it)}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerEnum("com.gridnine.jasmine.server.standard.model.rest.LayoutTypeDTJS"){com.gridnine.jasmine.server.standard.model.rest.LayoutTypeDTJS.valueOf(it)}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerEnum("com.gridnine.jasmine.server.standard.model.rest.TableColumnTypeDTJS"){com.gridnine.jasmine.server.standard.model.rest.TableColumnTypeDTJS.valueOf(it)}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerEnum("com.gridnine.jasmine.server.standard.model.rest.VerticalAlignmentDTJS"){com.gridnine.jasmine.server.standard.model.rest.VerticalAlignmentDTJS.valueOf(it)}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerEnum("com.gridnine.jasmine.server.standard.model.rest.HorizontalAlignmentDTJS"){com.gridnine.jasmine.server.standard.model.rest.HorizontalAlignmentDTJS.valueOf(it)}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerEnum("com.gridnine.jasmine.server.standard.model.rest.SortOrderTypeDTJS"){com.gridnine.jasmine.server.standard.model.rest.SortOrderTypeDTJS.valueOf(it)}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerEnum("com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionConditionDTJS"){com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionConditionDTJS.valueOf(it)}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.RestPropertyDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.RestPropertyDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.RestCollectionDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.RestCollectionDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.RestEntityDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.RestEntityDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.EnumDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.EnumDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.DomainEnumItemDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.DomainEnumItemDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.DomainEnumDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.DomainEnumDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.IndexPropertyDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.IndexPropertyDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.IndexCollectionDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.IndexCollectionDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.IndexDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.IndexDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.AssetDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.AssetDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.RestOperationDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.RestOperationDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.StandardButtonDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.StandardButtonDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.AutocompleteDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.AutocompleteDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.VMPropertyDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.VMPropertyDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.VMCollectionDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.VMCollectionDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.VMEntityDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.VMEntityDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.VSPropertyDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.VSPropertyDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.VSCollectionDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.VSCollectionDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.VSEntityDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.VSEntityDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.VVPropertyDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.VVPropertyDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.VVCollectionDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.VVCollectionDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.VVEntityDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.VVEntityDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.TableNextColumnDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.TableNextColumnDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.TableNextRowDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.TableNextRowDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.TextAreaDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.TextAreaDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.IntegerBoxDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.IntegerBoxDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.FloatBoxDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.FloatBoxDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.TextboxDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.TextboxDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.PasswordBoxDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.PasswordBoxDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.DateBoxDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.DateBoxDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.DateTimeBoxDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.DateTimeBoxDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.BooleanBoxDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.BooleanBoxDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.EnumSelectDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.EnumSelectDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.SelectDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.SelectDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.EntityAutocompleteDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.EntityAutocompleteDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.TileDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.TileDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.NavigatorDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.NavigatorDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.TextTableColumnDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.TextTableColumnDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.IntegerTableColumnDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.IntegerTableColumnDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.NavigationTableColumnDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.NavigationTableColumnDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.FloatTableColumnDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.FloatTableColumnDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.EnumTableColumnDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.EnumTableColumnDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.EntityTableColumnDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.EntityTableColumnDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.TableDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.TableDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.LabelDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.LabelDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.TableColumnDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.TableColumnDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.TableLayoutDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.TableLayoutDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.StandardViewDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.StandardViewDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.ListDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.ListDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.EditorDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.EditorDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.DialogDescriptionDTJS"){com.gridnine.jasmine.server.standard.model.rest.DialogDescriptionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.SortOrderDTJS"){com.gridnine.jasmine.server.standard.model.rest.SortOrderDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionStringValuesDTJS"){com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionStringValuesDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionEntityValuesDTJS"){com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionEntityValuesDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionDateValueDTJS"){com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionDateValueDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionDateTimeValueDTJS"){com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionDateTimeValueDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionDateIntervalValueDTJS"){com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionDateIntervalValueDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionDateTimeIntervalValueDTJS"){com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionDateTimeIntervalValueDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.sandbox.model.domain.WorkspaceSimpleCriterionEnumValuesDTJS"){com.gridnine.jasmine.server.sandbox.model.domain.WorkspaceSimpleCriterionEnumValuesDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionFloatValueDTJS"){com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionFloatValueDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionIntValueDTJS"){com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionIntValueDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.SimpleWorkspaceCriterionDTJS"){com.gridnine.jasmine.server.standard.model.rest.SimpleWorkspaceCriterionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.OrWorkspaceCriterionDTJS"){com.gridnine.jasmine.server.standard.model.rest.OrWorkspaceCriterionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.AndWorkspaceCriterionDTJS"){com.gridnine.jasmine.server.standard.model.rest.AndWorkspaceCriterionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.NotWorkspaceCriterionDTJS"){com.gridnine.jasmine.server.standard.model.rest.NotWorkspaceCriterionDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.ListWorkspaceItemDTJS"){com.gridnine.jasmine.server.standard.model.rest.ListWorkspaceItemDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.WorkspaceGroupDTJS"){com.gridnine.jasmine.server.standard.model.rest.WorkspaceGroupDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.WorkspaceDTJS"){com.gridnine.jasmine.server.standard.model.rest.WorkspaceDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.ListFilterStringValuesDTJS"){com.gridnine.jasmine.server.standard.model.rest.ListFilterStringValuesDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.ListFilterEntityValuesDTJS"){com.gridnine.jasmine.server.standard.model.rest.ListFilterEntityValuesDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.ListFilterDateIntervalValueDTJS"){com.gridnine.jasmine.server.standard.model.rest.ListFilterDateIntervalValueDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.ListFilterDateTimeIntervalValueDTJS"){com.gridnine.jasmine.server.standard.model.rest.ListFilterDateTimeIntervalValueDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.ListFilterEnumValuesDTJS"){com.gridnine.jasmine.server.standard.model.rest.ListFilterEnumValuesDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.ListFilterFloatIntervalValueDTJS"){com.gridnine.jasmine.server.standard.model.rest.ListFilterFloatIntervalValueDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.ListFilterIntIntervalValueDTJS"){com.gridnine.jasmine.server.standard.model.rest.ListFilterIntIntervalValueDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.ListFilterBooleanValuesDTJS"){com.gridnine.jasmine.server.standard.model.rest.ListFilterBooleanValuesDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.ListFilterDTJS"){com.gridnine.jasmine.server.standard.model.rest.ListFilterDTJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.RestFileJS"){com.gridnine.jasmine.server.standard.model.rest.RestFileJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.GetMetadataRequestJS"){com.gridnine.jasmine.server.standard.model.rest.GetMetadataRequestJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.GetMetadataResponseJS"){com.gridnine.jasmine.server.standard.model.rest.GetMetadataResponseJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.GetWorkspaceRequestJS"){com.gridnine.jasmine.server.standard.model.rest.GetWorkspaceRequestJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.GetWorkspaceResponseJS"){com.gridnine.jasmine.server.standard.model.rest.GetWorkspaceResponseJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.SaveWorkspaceRequestJS"){com.gridnine.jasmine.server.standard.model.rest.SaveWorkspaceRequestJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.SaveWorkspaceResponseJS"){com.gridnine.jasmine.server.standard.model.rest.SaveWorkspaceResponseJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.GetListRequestJS"){com.gridnine.jasmine.server.standard.model.rest.GetListRequestJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.GetListResponseJS"){com.gridnine.jasmine.server.standard.model.rest.GetListResponseJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.GetEditorDataRequestJS"){com.gridnine.jasmine.server.standard.model.rest.GetEditorDataRequestJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.GetEditorDataResponseJS"){com.gridnine.jasmine.server.standard.model.rest.GetEditorDataResponseJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.SaveEditorDataRequestJS"){com.gridnine.jasmine.server.standard.model.rest.SaveEditorDataRequestJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.SaveEditorDataResponseJS"){com.gridnine.jasmine.server.standard.model.rest.SaveEditorDataResponseJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.DeleteObjectRequestJS"){com.gridnine.jasmine.server.standard.model.rest.DeleteObjectRequestJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.DeleteObjectResponseJS"){com.gridnine.jasmine.server.standard.model.rest.DeleteObjectResponseJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.EntityAutocompleteRequestJS"){com.gridnine.jasmine.server.standard.model.rest.EntityAutocompleteRequestJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerClass("com.gridnine.jasmine.server.standard.model.rest.EntityAutocompleteResponseJS"){com.gridnine.jasmine.server.standard.model.rest.EntityAutocompleteResponseJS()}
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.RestPropertyDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.RestPropertyDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.RestCollectionDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.RestCollectionDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.RestEntityDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.RestEntityDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.EnumDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.EnumDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.DomainEnumItemDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.DomainEnumItemDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.DomainEnumDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.DomainEnumDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.IndexPropertyDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.IndexPropertyDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.IndexCollectionDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.IndexCollectionDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.IndexDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.IndexDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.AssetDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.AssetDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.RestOperationDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.RestOperationDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.StandardButtonDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.StandardButtonDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.AutocompleteDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.AutocompleteDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.VMPropertyDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.VMPropertyDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.VMCollectionDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.VMCollectionDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.VMEntityDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.VMEntityDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.VSPropertyDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.VSPropertyDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.VSCollectionDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.VSCollectionDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.VSEntityDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.VSEntityDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.VVPropertyDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.VVPropertyDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.VVCollectionDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.VVCollectionDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.VVEntityDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.VVEntityDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.TableNextColumnDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.TableNextColumnDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.TableNextRowDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.TableNextRowDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.TextAreaDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.TextAreaDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.IntegerBoxDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.IntegerBoxDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.FloatBoxDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.FloatBoxDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.TextboxDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.TextboxDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.PasswordBoxDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.PasswordBoxDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.DateBoxDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.DateBoxDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.DateTimeBoxDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.DateTimeBoxDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.BooleanBoxDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.BooleanBoxDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.EnumSelectDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.EnumSelectDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.SelectDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.SelectDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.EntityAutocompleteDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.EntityAutocompleteDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.TileDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.TileDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.NavigatorDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.NavigatorDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.TextTableColumnDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.TextTableColumnDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.IntegerTableColumnDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.IntegerTableColumnDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.NavigationTableColumnDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.NavigationTableColumnDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.FloatTableColumnDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.FloatTableColumnDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.EnumTableColumnDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.EnumTableColumnDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.EntityTableColumnDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.EntityTableColumnDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.TableDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.TableDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.LabelDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.LabelDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.TableColumnDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.TableColumnDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.TableLayoutDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.TableLayoutDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.StandardViewDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.StandardViewDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.ListDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.ListDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.EditorDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.EditorDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.DialogDescriptionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.DialogDescriptionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.SortOrderDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.SortOrderDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionStringValuesDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionStringValuesDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionEntityValuesDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionEntityValuesDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionDateValueDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionDateValueDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionDateTimeValueDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionDateTimeValueDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionDateIntervalValueDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionDateIntervalValueDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionDateTimeIntervalValueDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionDateTimeIntervalValueDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.sandbox.model.domain.WorkspaceSimpleCriterionEnumValuesDTJS::class, "com.gridnine.jasmine.server.sandbox.model.domain.WorkspaceSimpleCriterionEnumValuesDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionFloatValueDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionFloatValueDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionIntValueDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.WorkspaceSimpleCriterionIntValueDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.SimpleWorkspaceCriterionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.SimpleWorkspaceCriterionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.OrWorkspaceCriterionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.OrWorkspaceCriterionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.AndWorkspaceCriterionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.AndWorkspaceCriterionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.NotWorkspaceCriterionDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.NotWorkspaceCriterionDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.ListWorkspaceItemDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.ListWorkspaceItemDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.WorkspaceGroupDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.WorkspaceGroupDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.WorkspaceDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.WorkspaceDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.ListFilterStringValuesDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.ListFilterStringValuesDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.ListFilterEntityValuesDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.ListFilterEntityValuesDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.ListFilterDateIntervalValueDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.ListFilterDateIntervalValueDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.ListFilterDateTimeIntervalValueDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.ListFilterDateTimeIntervalValueDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.ListFilterEnumValuesDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.ListFilterEnumValuesDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.ListFilterFloatIntervalValueDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.ListFilterFloatIntervalValueDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.ListFilterIntIntervalValueDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.ListFilterIntIntervalValueDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.ListFilterBooleanValuesDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.ListFilterBooleanValuesDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.ListFilterDTJS::class, "com.gridnine.jasmine.server.standard.model.rest.ListFilterDTJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.RestFileJS::class, "com.gridnine.jasmine.server.standard.model.rest.RestFileJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.GetMetadataRequestJS::class, "com.gridnine.jasmine.server.standard.model.rest.GetMetadataRequestJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.GetMetadataResponseJS::class, "com.gridnine.jasmine.server.standard.model.rest.GetMetadataResponseJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.GetWorkspaceRequestJS::class, "com.gridnine.jasmine.server.standard.model.rest.GetWorkspaceRequestJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.GetWorkspaceResponseJS::class, "com.gridnine.jasmine.server.standard.model.rest.GetWorkspaceResponseJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.SaveWorkspaceRequestJS::class, "com.gridnine.jasmine.server.standard.model.rest.SaveWorkspaceRequestJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.SaveWorkspaceResponseJS::class, "com.gridnine.jasmine.server.standard.model.rest.SaveWorkspaceResponseJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.GetListRequestJS::class, "com.gridnine.jasmine.server.standard.model.rest.GetListRequestJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.GetListResponseJS::class, "com.gridnine.jasmine.server.standard.model.rest.GetListResponseJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.GetEditorDataRequestJS::class, "com.gridnine.jasmine.server.standard.model.rest.GetEditorDataRequestJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.GetEditorDataResponseJS::class, "com.gridnine.jasmine.server.standard.model.rest.GetEditorDataResponseJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.SaveEditorDataRequestJS::class, "com.gridnine.jasmine.server.standard.model.rest.SaveEditorDataRequestJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.SaveEditorDataResponseJS::class, "com.gridnine.jasmine.server.standard.model.rest.SaveEditorDataResponseJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.DeleteObjectRequestJS::class, "com.gridnine.jasmine.server.standard.model.rest.DeleteObjectRequestJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.DeleteObjectResponseJS::class, "com.gridnine.jasmine.server.standard.model.rest.DeleteObjectResponseJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.EntityAutocompleteRequestJS::class, "com.gridnine.jasmine.server.standard.model.rest.EntityAutocompleteRequestJS")
        com.gridnine.jasmine.web.core.utils.ReflectionFactoryJS.get().registerQualifiedName(com.gridnine.jasmine.server.standard.model.rest.EntityAutocompleteResponseJS::class, "com.gridnine.jasmine.server.standard.model.rest.EntityAutocompleteResponseJS")
    }
}